title: Carson DeSotel
author: Carson DeSotel
email: carson.desotel@gmail.com

description: > 
  This is a place to share some of the things I'm interested in, things I'm working on, and some of the lessons I've learned.
  
show_excerpts: true # set to true to show excerpts on the homepage

minima:
  social_links:
    github: Carson-DeSotel
    twitter: carson_desotel
    stackoverflow_username: 10751604/carson
    linkedin: carson-desotel

header-pages:
 - about.md
 - directory.html
 - projects.html

# Build settings 
theme: minima

# 
# Custom Configurations [ 05 - 19 - 2019 ]
# 

# https://github.com/barryclark/jekyll-now/blob/master/_config.yml
