title: Chez Carson
author: Carson DeSotel
email: carson.desotel@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Personal website with plans for hosting projects, blogs, etc.
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social_links:
    github: Carson-DeSotel
    twitter: carson_desotel
    stackoverflow: users/10751604/carson
    linkedin: carson-desotel

header-pages:
 - about.md
 - directory.html

# Build settings 
theme: minima

# 
# Custom Configurations [ 05 - 19 - 2019 ]
# 

# https://github.com/barryclark/jekyll-now/blob/master/_config.yml
