url: "https://www.carsondesotel.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Carson's Page" # the name of your site, e.g. ACME Corp.

sass: 
  sass_dir: _sass