# 
# Custom Configurations [ 05 - 19 - 2019 ]
# 

# https://github.com/barryclark/jekyll-now/blob/master/_config.yml

title: Chez Carson
author: Carson DeSotel
email: carson.desotel@gmail.com
avatar: /images/UK1jLwb-square_edit.jpg
description: > # this means to ignore newlines until "baseurl:"
  Personal website with plans for hosting projects, blogs, etc.
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  social-links:
    github: Carson-DeSotel
    twitter: totallycarson
    stackoverflow: users/10751604/carson
    linkedin: carson-desotel

# Build settings 
theme: minima
