title: Chez Carson
author: Carson DeSotel
email: carson.desotel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website with plans for hosting projects, blogs, etc.
# social links
twitter_username: @totallycarson
github_username:  @Carson-DeSotel

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
