baseURL = 'localhost:1313'
languageCode = 'en-us'
title = 'Carson DeSotel'

theme = 'carson'

# render iframes
[markup.goldmark.renderer]
 unsafe = true

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	subtitle="(he/him) | software developer | game master"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = 'resume'
url  = '/resume'
weight = 4